### ISSUE TITLE
How to make Emscripten's SDL window occupy the whole window?

### ISSUE THREAD

**Issue by kornerr** [kripken/emscripten#7106]
Hi.

I've only found information on full screen: http://kripken.github.io/emscripten-site/docs/api_reference/html5.h#fullscreen
However, I simply want to have a render window size be equal to html.body (occupy the whole browser page, not screen).

Any idea how to achieve it?

Thanks.

**Comment by kornerr** [comment]
Found a way to make canvas occupy the whole page: simply add the following CSS style into generated html:
```
#canvas {
    position: absolute;
    top: 0px;
    left: 0px;
    margin: 0px;
    width: 100%;
    height: 100%;
    overflow: hidden;
    display: block;
}
```
Found this clever hint here: http://floooh.github.io/2017/02/22/emsc-html.html

**Comment by dbeef** [comment]
Great answer, thanks @kornerr. If anyone wanted to additionally keep specific aspect ratio and center both vertically/horizontally:

```css
#canvas {                                                                                                                                                                         
    width: height * 1.777; /* 16:9 */                                                                                                                                             
    height: 100%;                                                                                                                                                                 
    overflow: hidden;                                                                                                                                                             
    display: block;                                                                                                                                                               
    position: absolute;                                                                                                                                                           
    top: 0; bottom: 0; left: 0; right: 0;                                                                                                                                         
    margin: auto;                                                                                                                                                                 
}     
```
